# Generated by Django 5.0.2 on 2024-02-19 16:30

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_id_alter_product_name_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=shop.models.generate_product_id, max_length=6, primary_key=True, serialize=False),
        ),
    ]
